syntax = "proto3";

package sadoku.preview.v1;

service PreviewService {
  rpc GetSession(GetSessionRequest) returns (GetSessionResponse);
  rpc GetStatistics(GetStatisticsRequest) returns (GetStatisticsResponse);
}

message GetSessionRequest {}

message GetSessionResponse {
  optional PullRequest pull_request = 1;
}

message PullRequest {
  string description = 1;
  uint32 number = 2;
  string title = 3;
  string url = 4;
}

message GetStatisticsRequest {}

message GetStatisticsResponse {
  CommentCount comment_count = 1;
  uint64 database_size = 2;
  uint64 document_count = 3;
}

message CommentCount {
  uint64 bot = 1;
  uint64 human = 2;
}
